services:

    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/postgresql/data
        volumes:
            - ./db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    api:
        container_name: api
        # build:
        #     context: .
        #     dockerfile: ./Dockerfile
        image: chiennn/ttodoapi:latest
        platform: linux/amd64
        restart: always
        ports:
            - 5001:5001
        environment:
            PORT: 5001
            DB_USER: postgres
            DB_HOST: postgres
            DB_DATABASE: postgres
            DB_PASSWORD: password
            DB_PORT: 5432
        depends_on:
            - postgres

    pgadmin:
        image: dpage/pgadmin4:latest
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: example@gmail.com
            PGADMIN_DEFAULT_PASSWORD: password
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8888:80"
        volumes:
            - ./pgadmin-data:/var/lib/pgadmin
        links:
            - "postgres:pgsql-server"
